apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kyikvly96-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kyikvly96-nodejs 
  name: kyikvly96-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: kyikvly96-nodejs 
